# Generated by Django 5.0.3 on 2024-05-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
    ]
